apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: grafana-image-exporter
  namespace: default
  labels:
    team: tbd
spec:
  image: is_set_from_pipeline
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secrets: false
  webproxy: true
  env:
    - name: GRAFANA_BASE_URL
      value: https://grafana.adeo.no
